[training]
dropout = 0.2
eps = 1e-5
learning_rate = 3e-4

[hyperparams]
# Technically only for training but we'll keep it here.
batch_size = 8
block_size = 256

num_embed = 384
num_heads = 4
num_layers = 4